# Generated by Django 4.2 on 2023-05-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_name_alter_product_status"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products_list",
            field=models.ManyToManyField(
                related_name="products", to="products.product"
            ),
        ),
    ]
