# Generated by Django 4.2 on 2023-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_name_alter_product_status"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products_list",
            field=models.ManyToManyField(
                blank=True, related_name="products_cart", to="products.product"
            ),
        ),
    ]
