# Generated by Django 4.2 on 2023-05-05 18:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0002_alter_cart_products_list"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="seller_list",
        ),
        migrations.AddField(
            model_name="cart",
            name="seller_list",
            field=models.ManyToManyField(
                related_name="cart_list", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
