# Generated by Django 4.2 on 2023-05-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_is_admin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
    ]
