# Generated by Django 4.2 on 2023-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("disponivel", "Disponivel"),
                    ("indisponivel", "Indisponivel"),
                ],
                default="disponivel",
                max_length=127,
            ),
        ),
    ]
