# Generated by Django 4.2 on 2023-05-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_alter_cart_products_list"),
        ("products", "0002_alter_product_name_alter_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cart",
            field=models.ManyToManyField(related_name="cart_products", to="cart.cart"),
        ),
    ]
