# Generated by Django 4.2 on 2023-05-08 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_product_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cart",
        ),
    ]
